homework4
kolike/keksogram pull request #7
Opened 2020-08-22 16:34 UTC by kolike

2020-08-30 15:08 UTC, KseniaFilippova commented on index.html
>                      <div class="effect-level__line">
зачем?

2020-08-30 16:01 UTC, KseniaFilippova commented
1. Не выполнены пункты ТЗ:
-изменение масштаба изображения;
-применение одного из заранее заготовленных эффектов;

2. Длина комментария не может составлять больше 140 символов - не работает

3. Закрытие формы редактирования изображения производится либо нажатием
на кнопку .upload-cancel , либо нажатием клавиши Esc - не реализовано

2020-08-30 18:15 UTC, KseniaFilippova requested changes

2020-08-30 18:16 UTC, KseniaFilippova commented on js/pictures.js
> +var MAX_HASHTAG_COUNT = 5;
MAX_HASHTAGS_COUNT

2020-08-31 15:44 UTC, kolike commented on index.html
>                      <div class="effect-level__line">
Да где-то экспериментировал

2020-08-31 15:45 UTC, kolike commented on js/pictures.js
> +  "Очень хорошее фото!",
Показалось, что негативных комментов много)

2020-08-31 15:46 UTC, kolike commented on js/pictures.js
> +uploadFileForm.addEventListener("change", function () {
я так понимаю в момент открытия окна формы

2020-08-31 15:49 UTC, kolike commented on js/pictures.js
> +var addPictureClickHandler = function (picture, index) {
Видимо по привычке) Поправил

2020-08-31 15:50 UTC, kolike commented on js/pictures.js
> +renderComment = function (pictureDescription) {
Саглы

2020-08-31 15:54 UTC, kolike commented on js/pictures.js
> +for (var i = 0; i < pictures.length; i++) {
поправил

2020-08-31 15:56 UTC, kolike commented on js/pictures.js
> +}
тут не понял, куда отступ? return вроде стоит с одним отступом от основной части объявления функции

2020-08-31 15:56 UTC, kolike commented on js/pictures.js
> +  }
а,  или ты имеешь ввиду отступ после "}"?

2020-08-31 16:01 UTC, kolike commented on js/pictures.js
> +    } else if (hashtags[i].charAt(0) !== "#") {
тут не понял слегка, просто else бы не сработал вроде как

2020-08-31 16:07 UTC, kolike commented on js/pictures.js
> +    } else if (hashtags.length > MAX_HASHTAG_COUNT) {
ponyal

2020-08-31 16:07 UTC, kolike commented on js/pictures.js
> +function isHashtagUnique(hashtags) {
ladno)

2020-09-12 11:27 UTC, DimFilippov requested changes
Красавчик) немного шлифонуть и будет конфэтка

2020-09-12 11:27 UTC, DimFilippov commented on js/pictures.js
> +  if (hashtags.length > MAX_HASHTAGS_COUNT) {
думаю эти проверки лучше перед фором сделать

2020-09-12 11:27 UTC, DimFilippov commented on js/pictures.js
>      var firstHashtag = hashtags[i].toLowerCase();
перед фором переносик сделай

2020-09-12 11:27 UTC, DimFilippov commented on js/pictures.js
> +  var scaleWas = scaleValue.value;
oldScale

2020-09-12 11:27 UTC, DimFilippov commented on js/pictures.js
> +  var scaleBecome = scaleWas.substring(0, scaleWas.length - 1) - SCALE_STEP;
newScale

2020-09-12 11:27 UTC, DimFilippov commented on js/pictures.js
> +  var scaleBecome = scaleWas.substring(0, scaleWas.length - 1) - SCALE_STEP;
че тут за магия происходит?)

2020-09-12 11:27 UTC, DimFilippov commented on js/pictures.js
> +  imageUploadPreview.classList.remove(`effects__preview--none`);
давай мы в форе удалим пройдясь по всем эффектам в effectList, а то нехорошо получилось

2020-09-12 14:11 UTC, kolike commented on js/pictures.js
> +var MAX_HASHTAGS_LENGTH = 20;
принял

2020-09-12 14:12 UTC, kolike commented on js/pictures.js
> +var effectList = document.querySelectorAll(".effects__radio");
В index.html  73 строка <ul class="effects__list"> ничего не выдумано)

2020-09-12 14:14 UTC, kolike commented on js/pictures.js
> +var buttonZoomOutLoadedPhoto = document.querySelector(
принял

2020-09-12 14:14 UTC, kolike commented on js/pictures.js
> +var buttonZoomInLoadedPhoto = document.querySelector(".scale__control--bigger");
принял

2020-09-12 14:15 UTC, kolike commented on js/pictures.js
> +function makeScaleDown() {
поправил, но разве функция не глагол? типо "сделай масштаб ниже"))

2020-09-12 14:15 UTC, kolike commented on js/pictures.js
> +function makeScaleUp() {
+

2020-09-12 14:17 UTC, kolike commented on js/pictures.js
> +renderComments = function (pictureDescription) {
хорошо, почему то руки сами тянутся написать function expression)

2020-09-12 14:18 UTC, kolike commented on js/pictures.js
> +  if (hashtags.length > MAX_HASHTAGS_COUNT) {
лады

2020-09-12 14:19 UTC, kolike commented on js/pictures.js
>      var firstHashtag = hashtags[i].toLowerCase();
лады

2020-09-12 14:20 UTC, kolike commented on js/pictures.js
> +  var scaleWas = scaleValue.value;
ok

2020-09-12 14:23 UTC, kolike commented on js/pictures.js
> +  var scaleBecome = scaleWas.substring(0, scaleWas.length - 1) - SCALE_STEP;
да все просто, в scaleWas записываем значение масштаба, потом в scaleBecome записываем это значение и удаляем знак "%", чтоб превратить строку в число, (я гуглил как убрать последний элемент строки), и из этого значения вычитаем шаг масштаба, равный 25 и доаляем снова знак "%")

2020-09-12 14:30 UTC, kolike commented on js/pictures.js
> +  imageUploadPreview.classList.remove(`effects__preview--none`);
я нашел способ проще)

2020-09-12 14:48 UTC, kolike commented on js/pictures.js
> +  imageUploadPreview.classList.remove(`effects__preview--none`);
а, нет, будем думать)

2020-09-17 18:46 UTC, DimFilippov requested changes
молодец)) почти

2020-09-17 18:46 UTC, DimFilippov commented on css/style.css
> +transform: scale(1);
че это? и че с табуляцией?

2020-09-17 18:46 UTC, DimFilippov commented on js/pictures.js
>    if (!isHashtagsUnique(hashtags)) {
это тоже перед фором

2020-09-17 18:46 UTC, DimFilippov commented on js/pictures.js
> +window.addEventListener("keydown", function (evt) {
у тебя два одинаковых обработчикам можно в один объединить

2020-09-19 14:15 UTC, kolike commented on js/pictures.js
> +window.addEventListener("keydown", function (evt) {
объединил, добавил еще к обработку, чтоб не закрывался BigPicture, если фокус там на комментах

2020-09-19 14:16 UTC, kolike commented on js/pictures.js
>    if (!isHashtagsUnique(hashtags)) {
+

2020-09-20 12:35 UTC, KseniaFilippova commented on js/pictures.js
>    if (!isHashtagsUnique(hashtags)) {
резолвь

2020-09-20 12:36 UTC, KseniaFilippova commented on js/pictures.js
> +window.addEventListener("keydown", function (evt) {
резолвь

2020-09-20 12:37 UTC, KseniaFilippova commented
можешь мерджить) мы не можем, ты нас в эту репу не добавил

2020-09-20 16:16 UTC, merged